"""empty message

Revision ID: 38240acea928
Revises: 9f6dd642044f
Create Date: 2021-03-21 14:50:52.761519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38240acea928'
down_revision = '9f6dd642044f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'product', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'date_updated')
    # ### end Alembic commands ###
